name: "[dunfell]-standard"

on:
  push:
    branches: master

jobs:
  qemux86:
    name: "qemux86 with standard options"
    env:
      MACHINE: qemux86
      BRANCH: dunfell

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: master
      - name: Update APT
        run: sudo apt-get update
      - name: Install Dependencies
        run: sudo apt-get -yq --no-install-suggests --no-install-recommends install build-essential chrpath diffstat gawk gcc-multilib git-core libsdl1.2-dev python3 socat texinfo unzip wget xterm
      - name: Check out poky
        run: git clone git://git.yoctoproject.org/poky.git/ -b $BRANCH poky
      - name: Setup poky
        run: source poky/oe-init-build-env
      - name: add meta-buildutils
        run: |
          source poky/oe-init-build-env
          bitbake-layers add-layer $(pwd)/..
      - name: prepare local.conf
        run: |
          source poky/oe-init-build-env
          echo 'INHERIT +="rm_work"' >> conf/local.conf
      - name: Bitbake parse
        run: |
          source poky/oe-init-build-env
          bitbake -p
          
